### ISSUE TITLE
Installation FAQ

### ISSUE THREAD

**Issue by riddle** [tsbehlman/Injector#1]
I’m a novice user of Safari extensions, could you possibly explain in a few steps how to turn this repository into a `.safariext` file, ready to be installed?

**Comment by tsbehlman** [comment]
That reminds me, I need to upload releases here. Builds are available at http://tbehlman.com/safari/Injector.safariextz

If you'd like to use the source code, you can enable the Develop menu in Safari in order to access the Extension Builder.  You won't be able to export a safariextz from there, but you can import and install the extension from source.

**Comment by riddle** [comment]
Thanks. Is there any possibility that the build you linked is an old one? I saw Retina and Yosemite patches in the commit list and what I just downloaded seems to look like the old User CSS extension (but with scripting ability).

**Comment by tsbehlman** [comment]
I'll release the current version soon, probably this afternoon.

**Comment by tsbehlman** [comment]
A release has been pushed to Github.
